name: Example workflow for Python using AQtive Guard AI-SPM Inventory Scan by SandboxAQ
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Run AI-SPM Inventory detection
        uses: sandbox-quantum/aispm-inventory-action@main
        with:
          aqg_instance: https://aispm-demo.aqtiveguard.com
          aqg_client_id: ${{ secrets.aq-f98c0c25ad82bd10209c1c2e4604af225e08e03d}}
          aqg_client_secret: ${{ secrets.f4b2a3eefd043c5d159c7f35bdfae8fe7fffdd4ad43c8b31dcebfde1c958595e}}
